custom: [ "https://buymeacoffee.com/vitalij_r2", "https://send.monobank.ua/jar/9r5bd6ejUC?f=enabled&t=mock-jdk-platform-logging", "https://next.privat24.ua/send/cblin", "https://mobile-app.pumb.ua/NaHVnD3xDZh1mscq7" ]
ko_fi: vitalij_r2
liberapay: vitalij_r2
